/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PengelolaanKRS;

/**
 *
 * @author alief
 */
public class FormLoginDosen extends javax.swing.JFrame {

    /**
     * Creates new form FormLoginDosen
     */
    public FormLoginDosen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PanelLoginDosen = new javax.swing.JPanel();
        LabelUsernameDosen = new javax.swing.JLabel();
        LabelPasswordDosen = new javax.swing.JLabel();
        TextFieldUsernameDosen = new javax.swing.JTextField();
        PasswordFieldPasswordDosen = new javax.swing.JPasswordField();
        ButtonMasukDosen = new javax.swing.JButton();
        ButtonKembaliDosen = new javax.swing.JButton();
        PanelGambarLoginDosen = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Dosen");

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 400));

        PanelLoginDosen.setBackground(new java.awt.Color(0, 102, 255));
        PanelLoginDosen.setPreferredSize(new java.awt.Dimension(292, 348));
        PanelLoginDosen.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelUsernameDosen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelUsernameDosen.setText("Username");
        PanelLoginDosen.add(LabelUsernameDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 243, -1, -1));

        LabelPasswordDosen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        LabelPasswordDosen.setText("Password");
        PanelLoginDosen.add(LabelPasswordDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 274, -1, -1));
        PanelLoginDosen.add(TextFieldUsernameDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 175, -1));
        PanelLoginDosen.add(PasswordFieldPasswordDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 271, 175, -1));

        ButtonMasukDosen.setBackground(new java.awt.Color(51, 255, 51));
        ButtonMasukDosen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonMasukDosen.setForeground(new java.awt.Color(255, 255, 255));
        ButtonMasukDosen.setText("Masuk");
        ButtonMasukDosen.setBorder(null);
        ButtonMasukDosen.setMargin(new java.awt.Insets(2, 3, 2, 3));
        PanelLoginDosen.add(ButtonMasukDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(106, 309, 60, 25));

        ButtonKembaliDosen.setBackground(new java.awt.Color(255, 255, 0));
        ButtonKembaliDosen.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ButtonKembaliDosen.setForeground(new java.awt.Color(51, 51, 51));
        ButtonKembaliDosen.setText("Kembali");
        ButtonKembaliDosen.setBorder(null);
        ButtonKembaliDosen.setMargin(new java.awt.Insets(2, 3, 2, 3));
        ButtonKembaliDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKembaliDosenActionPerformed(evt);
            }
        });
        PanelLoginDosen.add(ButtonKembaliDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 309, 70, 25));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GambarDanIcon/dosen.jpg"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout PanelGambarLoginDosenLayout = new javax.swing.GroupLayout(PanelGambarLoginDosen);
        PanelGambarLoginDosen.setLayout(PanelGambarLoginDosenLayout);
        PanelGambarLoginDosenLayout.setHorizontalGroup(
            PanelGambarLoginDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        PanelGambarLoginDosenLayout.setVerticalGroup(
            PanelGambarLoginDosenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, Short.MAX_VALUE)
        );

        PanelLoginDosen.add(PanelGambarLoginDosen, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 25, 292, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("LOGIN DOSEN");
        PanelLoginDosen.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 110, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("Silahkan isi NIDN sebagai username");
        PanelLoginDosen.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(PanelLoginDosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelLoginDosen, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonKembaliDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKembaliDosenActionPerformed
        FormMenu formMenu = new FormMenu();
        formMenu.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonKembaliDosenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLoginDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLoginDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLoginDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLoginDosen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLoginDosen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonKembaliDosen;
    private javax.swing.JButton ButtonMasukDosen;
    private javax.swing.JLabel LabelPasswordDosen;
    private javax.swing.JLabel LabelUsernameDosen;
    private javax.swing.JPanel PanelGambarLoginDosen;
    private javax.swing.JPanel PanelLoginDosen;
    private javax.swing.JPasswordField PasswordFieldPasswordDosen;
    private javax.swing.JTextField TextFieldUsernameDosen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
