/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package PengelolaanKRS;

import javax.swing.JOptionPane;

/**
 *
 * @author alief
 */
public class FormMenu extends javax.swing.JFrame {

    /**
     * Creates new form FormMenu
     */
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        LabelJudul = new javax.swing.JLabel();
        MenuBar = new javax.swing.JMenuBar();
        MenuBarLogin = new javax.swing.JMenu();
        MenuLoginAdmin = new javax.swing.JMenuItem();
        MenuLoginDosen = new javax.swing.JMenuItem();
        MenuLoginMahasiswa = new javax.swing.JMenuItem();
        MenuBarExit = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jDesktopPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelJudul.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        LabelJudul.setForeground(new java.awt.Color(255, 255, 255));
        LabelJudul.setText("SISTEM PENGELOLAAN KRS");
        jDesktopPane1.add(LabelJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 420, 90));

        MenuBarLogin.setText("Login");

        MenuLoginAdmin.setText("Admin");
        MenuLoginAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLoginAdminActionPerformed(evt);
            }
        });
        MenuBarLogin.add(MenuLoginAdmin);

        MenuLoginDosen.setText("Dosen");
        MenuLoginDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLoginDosenActionPerformed(evt);
            }
        });
        MenuBarLogin.add(MenuLoginDosen);

        MenuLoginMahasiswa.setText("Mahasiswa");
        MenuLoginMahasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLoginMahasiswaActionPerformed(evt);
            }
        });
        MenuBarLogin.add(MenuLoginMahasiswa);

        MenuBar.add(MenuBarLogin);

        MenuBarExit.setText("Exit");
        MenuBarExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuBarExitMouseClicked(evt);
            }
        });
        MenuBar.add(MenuBarExit);

        setJMenuBar(MenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuLoginDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLoginDosenActionPerformed
 FormLoginDosen formLoginDosen = new FormLoginDosen();
        formLoginDosen.setVisible(true);
        this.dispose(); // TODO add your handling code here:
    }//GEN-LAST:event_MenuLoginDosenActionPerformed

    private void MenuBarExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuBarExitMouseClicked
 int pilih=JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin keluar dari aplikasi ?",
            "Konfirmasi",JOptionPane.OK_CANCEL_OPTION);
        if (pilih == JOptionPane.OK_OPTION ) {
            System.exit(0);}
        else {
            JOptionPane.getRootFrame();}        // TODO add your handling code here:
    }//GEN-LAST:event_MenuBarExitMouseClicked

    private void MenuLoginAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLoginAdminActionPerformed
         FormLoginAdmin formLoginAdmin = new FormLoginAdmin();
        formLoginAdmin.setVisible(true);
        this.dispose();         // TODO add your handling code here:
    }//GEN-LAST:event_MenuLoginAdminActionPerformed

    private void MenuLoginMahasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLoginMahasiswaActionPerformed
 FormLoginMahasiswa formLoginMahasiswa = new FormLoginMahasiswa();
        formLoginMahasiswa.setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_MenuLoginMahasiswaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new FormMenu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelJudul;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JMenu MenuBarExit;
    private javax.swing.JMenu MenuBarLogin;
    private javax.swing.JMenuItem MenuLoginAdmin;
    private javax.swing.JMenuItem MenuLoginDosen;
    private javax.swing.JMenuItem MenuLoginMahasiswa;
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
